### ISSUE TITLE
Please create a Readme with usage instructions.

### ISSUE THREAD

**Issue by veelenga** [Ghrind/hydra#1]
Hey there. Thanks for this shard. Would be awesome to have some usage instructions so anyone could easily start using it.

Read this: https://twitter.com/masukomi/status/1000078773751025665

**Comment by Ghrind** [comment]
Hi! Thanks for your interest in this shard.

It is a way for me to learn crystal, so I'm not sure people would use it.

I will add a README :)

**Comment by Ghrind** [comment]
First draft of the README is already there, I will add more information.

**Comment by veelenga** [comment]
Cool, thanks
